# Generated by Django 5.2.6 on 2025-09-05 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sudokugame',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Easy'), ('normal', 'Normal'), ('medium', 'Medium'), ('hard', 'Hard'), ('death', 'Death')], default='normal', max_length=10),
        ),
    ]
